packages:
  - "packages/*"

allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true
catalog:
  "@faker-js/faker": ^10.6.0
  "@formkit/tempo": ^0.1.2
  "@supabase/supabase-js": ^2.112.3
  class-variance-authority: ^0.7.1
  dotenv: ^17.4.2
  drizzle-orm: ^0.45.2
  immutable: ^5.1.9
  neverthrow: ^8.2.0
  postgres: ^3.4.7
  solid-js: ^1.9.9
  uuid: ^14.0.1
  typescript: ^5.9.0
minimumReleaseAgeExclude:
  - "@astrojs/node@11.1.1"
  - astro@7.2.1
