CREATE TABLE "tmp"."grammar_point_label" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmp"."grammar_point_label_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grammarPointId" integer NOT NULL,
	"labelId" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tmp"."label" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmp"."label_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"color" varchar(7) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "label_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "tmp"."grammar_point_label" ADD CONSTRAINT "grammar_point_label_grammarPointId_grammar_point_tmp_id_fk" FOREIGN KEY ("grammarPointId") REFERENCES "tmp"."grammar_point_tmp"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmp"."grammar_point_label" ADD CONSTRAINT "grammar_point_label_labelId_label_id_fk" FOREIGN KEY ("labelId") REFERENCES "tmp"."label"("id") ON DELETE cascade ON UPDATE no action;