CREATE TABLE "tmp"."label" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tmp"."label_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"color" varchar(7) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "label_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "tmp"."label_to_grammar_point" (
	"label_id" integer NOT NULL,
	"grammar_point_id" integer NOT NULL,
	CONSTRAINT "label_to_grammar_point_label_id_grammar_point_id_pk" PRIMARY KEY("label_id","grammar_point_id")
);
--> statement-breakpoint
ALTER TABLE "tmp"."label_to_grammar_point" ADD CONSTRAINT "label_to_grammar_point_label_id_label_id_fk" FOREIGN KEY ("label_id") REFERENCES "tmp"."label"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tmp"."label_to_grammar_point" ADD CONSTRAINT "label_to_grammar_point_grammar_point_id_grammar_point_tmp_id_fk" FOREIGN KEY ("grammar_point_id") REFERENCES "tmp"."grammar_point_tmp"("id") ON DELETE cascade ON UPDATE no action;