apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 80
      containers:
        - image: ${IMAGE}
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PUBLIC_URL
              value: https://grumma-oss-55861693007.asia-northeast1.run.app
            - name: PUBLIC_API
              value: https://scala-notion-h2mjeyfyja-an.a.run.app/
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: AUTH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLIENT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DATABASE_URL
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SUPABASE_KEY
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
