name: Build and test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run check
    - run: bun run build
    - run: bun run test
    - run: bun run test:integration
