name: Build and test

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - uses: pnpm/setup@4700d737c3d7a2e7199f3d42a920f0bf7f34e411
        with:
          cache: true
      - run: pnpm run check
      - run: pnpm run --filter="*" build
      - run: pnpm run test
      - run: pnpm run test:integration
