name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      e2e-base-url:
        description: "Base URL for E2E tests"
        required: false
        default: "https://grumma.org"
jobs:
  test:
    permissions:
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c
        with:
          cache: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        env:
          E2E_BASE_URL: ${{ inputs.e2e-base-url }}
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
